# Generated by Django 3.2 on 2021-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0002_customer_merchant_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.FloatField(null=True),
        ),
    ]
