# Generated by Django 3.2 on 2021-04-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0003_order_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerConcerned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerview.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='merchantConcerned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerview.merchant'),
        ),
    ]
