# Generated by Django 3.2 on 2021-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0004_auto_20210415_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='startTime',
        ),
        migrations.AddField(
            model_name='order',
            name='orderCreated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eta',
            field=models.FloatField(default=-1),
        ),
    ]
