# Generated by Django 3.2 on 2021-04-15 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0005_auto_20210415_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderCreated',
            field=models.TimeField(default=datetime.datetime(2021, 4, 15, 17, 21, 32, 205290, tzinfo=utc)),
        ),
    ]
