# Generated by Django 3.2 on 2021-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0006_alter_order_ordercreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderCreated',
            field=models.TimeField(auto_now=True),
        ),
    ]
